export const currentSkills = [
    "Semantic & accessible HTML",
    "JavaScript ES6+",
    "CSS BEM convention",
    "CSS Grid",
    "CSS Flexbox",
    "Responsive Web Design",
    "Markdown",
    "Immutability",
    "React",
    "React Router",
    "React Hooks",
    "Redux-Saga",
    "Redux (Toolkit)",
    "Error handling",
    "Promises, Async/Await",
    "NPM",
    "Git",
    "GitHub Pull Requests & Review",
    "Teamwork",
    "Trello",
    "Scrum",
    "Figma",
    "Working with API (fetch, axios)",
];

export const skillsToLearn = [
    "TypeScript",
    "Vue.js",
    "Node.js",
    "Unit testing",
    "React Context",
    "Cypress",
    "Python",
];